# Generated by Django 6.0.5 on 2026-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_outlet_user_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletapikey',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin access'),
        ),
    ]
