# Generated by Django 6.0.5 on 2026-05-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('outlet', models.ForeignKey(limit_choices_to={'outlet_type': 'DEALER'}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='network.outlet', verbose_name='Dealer center')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock item',
                'verbose_name_plural': 'Stock items',
                'unique_together': {('outlet', 'product')},
            },
        ),
    ]
